# Generated by Django 2.0.13 on 2020-05-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(default='未知', max_length=10, verbose_name='教师年龄'),
        ),
    ]
