# Generated by Django 2.0.13 on 2020-05-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.TextField(default='', max_length=10, verbose_name='机构头衔'),
        ),
    ]
