# Generated by Django 2.0.13 on 2020-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vedio_url',
            field=models.CharField(default='', max_length=100, verbose_name='视频链接'),
        ),
    ]
