# Generated by Django 2.0.13 on 2020-05-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
        ('courses', '0007_video_vedio_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='课程老师'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vedio_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='视频时长(分钟数)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vedio_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='视频链接'),
        ),
    ]
