# Generated by Django 2.0.13 on 2020-05-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200508_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_knowledge',
            field=models.CharField(default='', max_length=100, verbose_name='课程需知'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_target',
            field=models.CharField(default='', max_length=120, verbose_name='课程目标'),
        ),
    ]
